/**
 * Generates supabase/migrations/*_demo_seed.sql from the sample workbook using the same parsers the app uses.
 * Run: npm run seed:build
 */
import { readFileSync, writeFileSync } from "node:fs";
import { applyFormulations, extractFormulations, mergeSamples } from "../lib/analysis/merge";
import { DEFAULT_TOLERANCES } from "../lib/analysis/tolerances";
import { sheetSummaries, toFormulationRows, toSampleRows, type LocatedSample } from "../lib/import/payload";
import { parseSheet } from "../lib/parsers";
import { readWorkbook } from "../lib/parsers/readWorkbook";

const WORKBOOK = "tests/fixtures/sample-data.xlsx";
const OUT = "supabase/migrations/20260930000004_demo_seed.sql";

const id = (n: number) => `00000000-0000-4000-a000-${String(n).padStart(12, "0")}`;

const ORGS = [
  {
    id: id(1),
    name: "Customer A",
    mills: [{ id: id(101), name: "Escondido mill" }],
    locations: [
      { id: id(201), name: "Location A", mill: id(101), sheets: ["Ex3 NIR vs formula (Loc A)", "Ex2 NIR export"] },
      { id: id(202), name: "Location B", mill: id(101), sheets: ["Ex3 NIR vs formula (Loc B)", "Ex1 Lab analysis report"] },
    ],
  },
  {
    id: id(2),
    name: "Customer D",
    mills: [{ id: id(102), name: "Mill D" }],
    locations: [
      { id: id(203), name: "Location 1", mill: id(102), sheets: ["D1 Location 1"] },
      { id: id(204), name: "Location 2", mill: id(102), sheets: ["D1 Location 2"] },
    ],
  },
  {
    id: id(3),
    name: "Customer F",
    mills: [
      { id: id(103), name: "Mill F-North" },
      { id: id(104), name: "Mill F-South" },
    ],
    locations: [
      { id: id(205), name: "Site F1", mill: id(103), sheets: ["F1 Analyses", "Ex4 Analyses vs intended"] },
      { id: id(206), name: "Site F2", mill: id(104), sheets: ["F2 Analyses"] },
    ],
  },
];

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const sheets = new Map(readWorkbook(readFileSync(WORKBOOK)).map((s) => [s.name, s.grid]));
const sql: string[] = [
  "-- Demo data generated by scripts/build-seed.ts from the sample workbook. Do not edit by hand.",
  "",
];

for (const org of ORGS) {
  sql.push(`insert into public.organizations (id, name, is_demo) values (${q(org.id)}, ${q(org.name)}, true);`);
  for (const m of org.mills) sql.push(`insert into public.feed_mills (id, org_id, name) values (${q(m.id)}, ${q(org.id)}, ${q(m.name)});`);
  for (const l of org.locations)
    sql.push(`insert into public.locations (id, org_id, name, mill_id) values (${q(l.id)}, ${q(org.id)}, ${q(l.name)}, ${q(l.mill)});`);
  for (const t of DEFAULT_TOLERANCES)
    sql.push(
      `insert into public.tolerance_rules (org_id, nutrient, mode, watch_low, watch_high, action_low, action_high, intended_offset) values (${q(org.id)}, ${q(t.nutrient)}, ${q(t.mode)}, ${t.watchLow ?? "null"}, ${t.watchHigh ?? "null"}, ${t.actionLow ?? "null"}, ${t.actionHigh ?? "null"}, ${t.intendedOffset});`,
    );

  const parses = org.locations.flatMap((l) =>
    l.sheets.map((name) => {
      const p = parseSheet(name, sheets.get(name)!);
      return { p, samples: p.samples.map((s): LocatedSample => ({ ...s, format: p.format, locationId: l.id })) };
    }),
  );
  const { merged } = mergeSamples(parses.flatMap((x) => x.samples));
  applyFormulations(merged, extractFormulations(merged));
  const located = merged as LocatedSample[];

  sql.push(
    `select public.import_feed_upload(${q(org.id)}, ${json({
      file_name: "Sample Data.xlsx",
      sheets: sheetSummaries(parses.map((x) => x.p)),
    })}, ${json(toSampleRows(located))}, ${json(toFormulationRows(located))});`,
  );
  sql.push("");
  console.log(`${org.name}: ${located.length} samples`);
}

writeFileSync(OUT, sql.join("\n"));
console.log(`wrote ${OUT}`);
